name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: numbqq/fenix:latest
      options: --user 0

    steps:
      - uses: actions/checkout@v5
        with:
          repository: 'rclaveau-tech/fenix'
          ref: 'rtm'

      - name: Add dependencies
        run: apt install libdw-dev libssl-dev libssl-dev:arm64

      - name: Set environement variable for the build and make the debian packages
        run: |
          . env/setenv.sh -q -s  KHADAS_BOARD=VIM4 LINUX=rtm UBOOT=2019.01 DISTRIBUTION=Ubuntu DISTRIB_RELEASE=noble DISTRIB_RELEASE_VERSION=24.04 DISTRIB_TYPE=server DISTRIB_ARCH=arm64 INSTALL_TYPE=SD-USB COMPRESS_IMAGE=yes
          make kernel-deb
        shell: bash

      - name: Upload the new packages built
        uses: actions/upload-artifact@v4.6.2
        with:
          path: build/images/*
